server:
  port: 8081
cas:
  #后端服务地址
  client-host-url: http://127.0.0.1:8081
  #cas认证中心地址
  server-url-prefix: http://127.0.0.1:8443/cas
  #cas认证中心登录地址
  server-login-url: http://127.0.0.1:8443/cas/login
  validation-type: cas3

